server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://120.77.221.159/account?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: Tan@8888
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  thymeleaf:
    prefix: classpath:/templates/
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
    typeAliasesPackage: com.jsptpd.gayg.modules
