server:
  port: 9001
  servlet:
    context-path: /brand
spring:
  messages:
    basename: i18n/messages
  thymeleaf:
  datasource:
    url: jdbc:mysql://120.77.221.159/CQProxy?seUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Tan@8888
#  mvc:
#    favicon:
#      enabled: true


